### ISSUE TITLE
anti-suffocation teleport

### ISSUE THREAD

**Issue by nathen418** [piotrwyrw/AntaresPrison#12]
Make the teleportation point (X, Y, Z, pitch, roll, yaw) that a player is teleported to when the mine resets configurable in mines.yml.

Also, prevent the player from suffocating on mine regen. Teleportation is not always reliable.

**Comment by nathen418** [comment]
This can be split into 2 issues if needed

**Comment by piotrwyrw** [comment]
Implemented in 1169a075de04584bdaecb6d27b6a948ae66461cf
