### ISSUE TITLE
Players able to skip mine tiers using /tpa

### ISSUE THREAD

**Issue by nathen418** [piotrwyrw/AntaresPrison#14]
**Describe the bug**
When a player without the permission **prisons.skip_room** is inside a room they have not bought the ticket for, they do not get kicked back to the previous mine. The plugin only rejects people going thru doorways but does not block tpa requests by kicking the player back.

**To Reproduce**
1. Have a friend in a higher mine than you.
2. Tpa to them.

**Expected behavior**
The player gets kicked back to the room they were in before the teleport event.

**Actual Behavior**
The player is able to stay in the room and not get kicked back.

**Screenshots**

**Desktop (please complete the following information):**
 - Version [1.3]

**Comment by piotrwyrw** [comment]
Fixed in 1169a075de04584bdaecb6d27b6a948ae66461cf
