### ISSUE TITLE
gui /mine command

### ISSUE THREAD

**Issue by nathen418** [piotrwyrw/AntaresPrison#15]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A /mines command similar to most prisons server. it would open a GUI with all the mines showing in it. you can click on the highest mine tier that you have access to it and warp straight there

**Describe alternatives you've considered**
Using a GUI plugin in place of this but it would be hard to set up and the prisons plugin should have something like this built in

**Additional context**
See Screenshots for context:
![2020-10-24_20 51 58](https://user-images.githubusercontent.com/23101313/97097116-d147f400-163a-11eb-83a6-0781dbb8741e.png)
![2020-10-24_20 51 54](https://user-images.githubusercontent.com/23101313/97097117-d3aa4e00-163a-11eb-9faf-9da1a6153e95.png)

**Comment by piotrwyrw** [comment]
This feature will be added after a major rewrite of the plugin.
