### ISSUE TITLE
Some spam of plugin messages in chat

### ISSUE THREAD

**Issue by nathen418** [piotrwyrw/AntaresPrison#3]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**  
Please reduce the number of times the "You can not break that block here" message appears or allow it to be disabled. It is really annoying and fills the screen.

**Describe alternatives you've considered**
setting the message to be: ' ' this is ineffective because you still see the prefix showing up in chat.

**Additional context**
See attached images:
[Image 1](https://media.discordapp.net/attachments/696177039325265970/769373082963935272/2020-10-23_20.31.46.png?width=1284&height=669)  
[Image2](https://media.discordapp.net/attachments/696177039325265970/769373070279704576/2020-10-23_20.32.14.png?width=1284&height=669)

**Comment by piotrwyrw** [comment]
Implemented in be4ced314a14d221f8a9fb2ef2e7d34cd34fcf09
