### ISSUE TITLE
Issue with using /prison balance {player}

### ISSUE THREAD

**Issue by nathen418** [piotrwyrw/AntaresPrison#9]
**Describe the bug**
When a user with the permission **prisons.other_balance** runs the command /prison balance {player} it does not show up for that player. It shows up on the player's screen that you were trying to see the balance of. See attached files.

**Expected behavior**
The player's balance that you are trying to find the balance of shows up on the person's screen that runs the command.

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Client [Optifine 1.16.3-OptiFine_HD_U_G4_pre1]
 - Version [1.2]

**Additional context**

**[Video1](https://cdn.discordapp.com/attachments/696177039325265970/769384054726328350/2020-10-23_21-12-56.mp4)** Is of the player running the command and having the output not show on their screen.  
\
![2020-10-23_21 13 16](https://user-images.githubusercontent.com/23101313/97065789-b790a900-1575-11eb-8c7e-d4faad7691d4.png)

See attached files

**Comment by piotrwyrw** [comment]
Implemented in 2ab62581690809b316fadf3fdd089f43fa27c35d
